const LIKE_NOTIFICATION = "LIKE_NOTIFICATION";
const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";

export {LIKE_NOTIFICATION, DELETE_NOTIFICATION, SET_NOTIFICATIONS};